apiVersion: v1
kind: PersistentVolume
metadata:
  name: coursier-pv
  labels:
    name: coursier-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /export/coursier
    server: 127.0.0.1
  persistentVolumeReclaimPolicy: Recycle
