kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ivy2-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
      matchLabels:
        name: "ivy2-pv"
