apiVersion: v1
kind: PersistentVolume
metadata:
  name: ivy2-pv
  labels:
    name: ivy2-pv
spec:
  capacity:
    storage: 1Gi 
  accessModes:
  - ReadWriteMany 
  nfs: 
    path: /export/.ivy2
    server: 127.0.0.1
  persistentVolumeReclaimPolicy: Retain
