apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  labels:
    name: jenkins-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /export/jenkins
    server: 127.0.0.1
  persistentVolumeReclaimPolicy: Retain
