kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: csw-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
      matchLabels:
        name: "csw-pv"
