apiVersion: v1
kind: PersistentVolume
metadata:
  name: ws-pv
  labels:
    name: ws-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteMany
  nfs:
    path: /export/jobs
    server: 127.0.0.1
  persistentVolumeReclaimPolicy: Recycle
