kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ws-pvc2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
      matchLabels:
        name: "ws-pv2"
