apiVersion: v1
kind: PersistentVolume
metadata:
  name: coursier-pv
  labels:
    name: coursier-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  nfs:
    path: /root/.coursier
    server: 127.0.0.1
  persistentVolumeReclaimPolicy: Recycle