apiVersion: v1
kind: PersistentVolume
metadata:
  name: ivy2-pv
  labels:
    name: ivy2-pv
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /root/.ivy2
    server: 127.0.0.1
  persistentVolumeReclaimPolicy: Recycle