apiVersion: v1
kind: PersistentVolume
metadata:
  name: workspace-pv
  labels:
    name: workspace-pv
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /root/csw-prod
    server: 127.0.0.1
  persistentVolumeReclaimPolicy: Recycle